version: '3'

services:
  strapi:
    container_name: strapi
    build: .
    environment:
        - NODE_ENV=production
        - DATABASE_CLIENT=mongo
        - DATABASE_HOST=db
        - DATABASE_PORT=27017
        - DATABASE_NAME=strapi
        - DATABASE_USERNAME=
        - DATABASE_PASSWORD=
        - DATABASE_AUTHENTICATION_DATABASE=strapi
    ports:
        - 1337:1337
    volumes:
        - ./public:/api/public
    depends_on:
        - db
    command: 'npm run strapi dev'
  db:
    container_name: mongo
    image: mongo
    environment:
        - MONGO_INITDB_DATABASE=strapi
    ports:
        - 27017:27017
    volumes:
        - ./db:/data/db
    restart: always
