name: Integration CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build and test Frontend
      working-directory: ./frontend/
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true

    - name: Build and test Backend
      working-directory: ./backend/
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true

  system-test:
    runs-on: ubuntu-latest
    needs: build # make sure the build and unit testing worked first
    steps:
        - uses: actions/checkout@v2
        - name: Run Docker Compose
          working-directory: .
          run: docker-compose up -d --build

        # TODO: Add system tests here

        # Bring containers back down after the tests
        - name: Purge Containers
          working-directory: .
          run: docker-compose down
